name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python brahmali.py
      - run: cd 'Ajahn Brahmali' && zip -r ../brahmali.zip .
      - name: Calculate Version
        run: echo "::set-output name=version::0.${{ github.run_number }}.0"
        id: version
      - name: Create VNM File
        run: |
          echo '{
            "folder": "Ajahn Brahmali",
            "more_info": "https://github.com/${{ github.repository }}",
            "version": "${{ steps.version.outputs.version }}",
            "requires": {
            },
            "zip": "https://github.com/obu-labs/brahmali-vinaya-notes/releases/download/v${{ steps.version.outputs.version }}/brahmali.zip"
          }' > brahmali.vnm
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          body: |
            Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            brahmali.zip
            glossary.json
            brahmali.vnm
