name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python brahmali.py
      - uses: obu-labs/vinaya-notes-module-releaser@main
        id: releaser
        with:
          path: Ajahn Brahmali
          metadata_file: metadata.yaml
      - run: gh release upload v${{ steps.releaser.outputs.version }} glossary.json
